get:
  -
    -
    -
    -
    - student
    -
  -
    - 1
    -
    -
    - student
    -
  -
    - 1
    - 2
    -
    - student
    -
  -
    - 1
    - 2
    - 陈宛茹
    - student
    -
  -
    -
    -
    -
    - manager
    -
  -
    -
    -
    -
    - manager
    - 3
  -
    -
    -
    -
    - manager
    - 4
  -
    -
    -
    - 胡石
    - manager
    - 4


