id: 3491403
schoolId: 1
schoolName: 南京河西外国语学校小学部
token: eyJhbGciOiJSUzI1NiJ9.eyJpZCI6MzQ5MTQwMywidXNlck5hbWUiOiLmiLTlubMiLCJleHAiOjE2Njk0NDcyODV9.dXPs-WGqUrBe0AnwYHUPPBHfQdcE2LYHO1B3AV6jUBpr-VyojoycnYAL1knC4XVdLKhWv03h8qVAJB06H0jU39ZqCyRL5Pneoa1Hj334YPeLJj8YT6yNgJPllt4a728YJo5iylH9rTmKyre4_eU6-Oj5j16-pNVzUbOIjVSJ2VU
